### ISSUE TITLE
w32tm to NTP server 

### ISSUE THREAD

**Issue by stevogray** [Staars/Tasmota_UBX_GPS#1]
Hello! I couldn't find another way to contact you.
I found out about your driver and it's inclusion in Tasmota from: https://esp8266hints.wordpress.com/2020/03/06/using-a-gps-with-tasmota-part-ii/

Thank you! Looks pretty good. I'm new to Tasmota.

I have followed along and have got Tasmota configured to collect location information from a uBlox module. Location is shown, NTP server starts and responds to requests.
I'm stumped now by two challenges:
- How do I get the NTP server to start automatically following ESP restart?
- How do I get w32tm (Windows10 time service) to sync using the ESP NTP server? I've tried connecting as a client only (using flag to force client requests, 0x8 - see https://kb.meinbergglobal.com/kb/time_sync/timekeeping_on_windows/configuring_w32time_as_ntp_client). Doesn't work. Any ideas?
Steve

**Comment by Staars** [comment]
Hi,

Thanks for your interest.
To always start the ntp-server after boot simply use a rule.
Example:
`Rule1 on system#boot do sensor60 9 endon`
(Do not forget to activate with `rule1 on`)

Regarding the Win10-question I fear, that I can not help as I am not a windows user. Maybe my daughter allows me to interrupt her hard work on her gaming PC ;) (I can not promise anything)

Christian

**Comment by stevogray** [comment]
Thanks for the fast reply.
I didn't know about rules (new to Tasmota). Good idea.

I've had a very frustrating evening - all of my ESP8266 modules are
refusing to take the program or to stay connected to wifi. Maybe the FTDI
adapter. Very frustrating. I think using NTP for windows (link below) and
stopping the default w32tm service will work. I wanted to try it before
replying, but can't get any of the ESP8266 to stay connected to the wifi
network for more than a minute!! Haven't even got the GPS board connected
today...
https://www.meinbergglobal.com/english/sw/ntp.htm#ntp_stable

Steve

**Comment by stevogray** [comment]
I _think_ my problem has been power supply. ESP8266 seems to be working now from a Li-ion battery, after a full day invested(?) lost(?) to this :-)

The rule works well, thanks.
The NTP software I linked above does add an NTP client to windows which will connect to the Tasmota based NTP server. But I gave up waiting for the NTP client to accept the Tasmmota source and sync the clock. Maybe it will eventually. At least it can see the source (unlike w32tm).

Thanks!
(PS: are you still going to look at adding a PPS input?)

**Comment by Staars** [comment]
I know the feeling of testing for several hours with the result of finding out, that the personal theory of how the things work Or fail is completely wrong 🤦‍♂️.

PPS may come, but I do not expect miracles resultwise. Delays will be introduced in other corners of the ESP8266-Tasmota-WLAN-combination anyway.

Keep in mind that this driver is (hopefully) a nice tinker toy or a better-than-nothing fallback. If the regular NTP-server options are accessible, these are recommended in the first place.
